### ISSUE TITLE
New user walkthrough missing

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#37]
When I signed up it did not walk me through the new users screens.
We should double check this.

**Comment by volkzayaz** [comment]
Need @kostya-p-dev, assistance here.

Please modify responses for methods `/auth/convert-token/` and `/auth/verify-phone/` to the following structure:

      {"data" : {
                          "user" : .... ////current response of authorized user
                          "isNew" : true/false /////flag that indicates if user was just created or it's regular Login
                     }
      }

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
@jmatheson, please verify in 0.0.10 when it's ready and close the ticket if issue is resolved

**Comment by jmatheson** [comment]
I am not sure how to test this. I just installed v.10 and it did not appear before or after I logged in with Facebook

**Comment by volkzayaz** [comment]
You were not presented the screen, because you're not new to OnMe. You already had an account in the database. Walkthrough will be presented only for newly registered users.

The easiest way to test is to use login using phone number which is not a registered user in OnMe. @jmatheson maybe you can use your working phone or your wife's phone.

**Comment by jmatheson** [comment]
Is this because of the UUID hack? How did it know i was not a new user when I installed the app and was not logged in??

**Comment by volkzayaz** [comment]
Verify in 0.0.13

**Comment by jmatheson** [comment]
works
