### ISSUE TITLE
No profile photo

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#47]
I have no profile photo, but I have linked my facebook account.
I don't understand how to get my profile photo in there.

**Comment by volkzayaz** [comment]
We discussed it here #21 
App fills profile info only during sign up. Upon linking additional auth providers data is not filled because it might overwrite existing values.
User should manually change details in settings.
Perhaps it is worth adding UI for updating profile picture?

**Comment by jmatheson** [comment]
My preference is to just use my current FB photo at all times. That's how v1 works.
At a minimum we should have one shot at setting a photo the first time you link FB, regardless of when you set up your account.

**Comment by volkzayaz** [comment]
As we discussed earlier, user might have his photo set from twitter sign up. Overwritting image by facebook, might be unexpected.
Same applies to name, birthday, email.
I strongly recommend you to stick to "fill only on register" rule. Otherwise we'll have a lot of issues like:
"Sign up with twitter, linked phone, unlinked twitter, linked facebook => account has mixed photo/name from phone number and twitter and facebook"

Or let's introduce another solid rule instead of "first wins".

**Comment by volkzayaz** [comment]
[Josh] "We should fill blank info upon sign up or linking accounts"

**Comment by volkzayaz** [comment]
@kostya-p-dev, as per received comments, please update logic for API method `/api/join_social/`

New logic contains following rules:
1) Contrary to current implementation API should request user social profile details. We used to do this only in `/auth/convert-token/`.
2) Empty values in `name`, `email`, `profilePhoto`, `birthday` should be filled with data from step 1 if it is available. Values should **NOT** be overwritten.

Example: Carl signed up using his twitter. App automatically retrieved his twitter name "carlo" and used as his `name` in app. Twitter account did not contain profile photo or email or birthday.
Later Carl link his facebook. App automatically retrieves his name( "Carl Johnson" ), profile picture and birthday. 
App should now set Carl's birthday and profile picture, because they were empty fields. But app should not update Carl's name to "Carl Johnson" because user already has a name set up. Resulting User would look like:
`name=carlo` `picture=http://image.png` `birthday=04/07/1983`

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
fixed in 0.0.17.
@jidulberger, @jmatheson please verify and close issue

**Comment by jmatheson** [comment]
@jidulberger  told me I have a profile photo now, so I am assuming it works as I logged out and back in again.
