### ISSUE TITLE
Favorites not working for buying a drink

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#54]
The app used to work that if a recipient had favorites there would be a button to tap at the bottom of the venue screen that said Josh's favorites (when choosing Josh). Now I can not see any of Josh's favorite venues to buy him at drink at one of his favorites.

Please review the code from the old version of the app. The expectation is that the functionality of favorites to work exactly like it used to work.

**Comment by volkzayaz** [comment]
What if recipient is outsider, or it is empty? We shouldn't display tabBar at all?

**Comment by volkzayaz** [comment]
I inspected the code. Having that it couldn't be compiled it's quite hard to understand what is the expected behaviour.
@jmatheson, can you help me restoring the requirements for Venue choosing screen.

According to the code there can be 3 tabs in the bottom: 
1) Nearby Venues. (appears always)
2) My favorite Venues. (depends on conditions that seem to always evaluate to true. Should this screen be present at all? If so, is it present always? )
3) Chosen User favorite Venues. (Seems like this is shown only if valid recipient was chosen earlier)

**Comment by volkzayaz** [comment]
In 0.0.14 implemented showing of tab Bar when recipient is a database user. Displaying favorite venues of selected recipient

**Comment by volkzayaz** [comment]
[vlad]
How many tabs are there in Choose Venue screen?
josh [4:38 PM] 
sure, happy to help
I believe it's (3) when the recipient is selected
[4:39]  
Nearby + Recipients Favs + My favs
[4:39]  
(when the recipient has favorites)

**Comment by jidulberger** [comment]
Can we display the recipient's first name (not last) here? Some user's are going to break this format otherwise.

**Comment by volkzayaz** [comment]
done in 0.0.15.
@jidulberger, please verify

**Comment by jmatheson** [comment]
Josh's favorite should read Josh's Favorites

**Comment by jidulberger** [comment]
If the person's name ends in an 's', include only the apostrophe, not an additional 's'.  Also - for the recipient's favorites, it should be 'Favorites' with a capital 'F' and plural 's' at the end of favorite.

**Comment by volkzayaz** [comment]
0.0.16
