### ISSUE TITLE
Rebuild HokoLinks

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#89]
Please give a time estimate for this one if we are to build up front.

Use case 1
- I buy user bob@gmail.com a drink. Bob does not have the app.
- Bob gets the email and clicks through the link from his computer OR android device (any non iOS device). If possible we should probably limit to anything that our app does not support (ie also open web if it is say iOS9, is that possible?)
    - This will open the drink on the webview (ie with the drink ID to reference what drink it is)

Use case 2
- I buy user bob@gmail.com a drink. Bob does not have the app.
- Bob gets the email and clicks through the link from his iOS device
    - This will open the app store to our app for download
    - When the user opens the app it will show their drink immediately (we might want to discuss how this used to work on our next call), then they claim the drink if it is unclaimed. If the drink has already been claimed then an error is thrown

Use case 3
- I buy user bob@gmail.com a drink. Bob has the app, but that email address is not tied to his account.
- Bob clicks through the email and it opens the drink in the app. He is the able to view it and any videos and then claim it by confirming that is his email address

These should also apply not only for email but also for tweeted drinks or drinks sent via SMS in order to claim them. I am perfectly ok with people who have twitter viewing a drink or video that is not actually their own (if they end up seeing the link).

**Comment by jmatheson** [comment]
Example link for a drink I purchased for a user's twitter handle that is not on our platform.
https://onme.link/Zvsz8RV

**Comment by volkzayaz** [comment]
@jmatheson,

> Use case 1 If possible we should probably limit to anything that our app does not support (ie also open web if it is say iOS9, is that possible?)
Yes, I think WebBrowsers provide "Agent" field which should contain platform and OS version.

> Use case 2 When the user opens the app it will show their drink immediately (we might want to discuss how this used to work on our next call). 
Current implementation does not navigate user to drink upon app downloading. User needs to click on the deeplink again upon app installation to be navigated to the drink.
Also if user has App installed but he is logged out, app does not navigate user to the drink. He needs to login first. We implemented it intentionally, but let me know if it's a bug,
Based on [this](http://support.hokolinks.com/what-is-a-deferred-deep-link/), Hoko saved device specific info via WebView, associated it with drink and upon launch queried server with device specific info. Not impossible, but should be implemented carefully.

> Use case 3 Bob clicks through the email and it opens the drink in the app. He is the able to view it and any videos and then claim it by confirming that is his email address.
Currently the confirmation - is having the same email as associated drink. For example, drink was bought for bob@gmail.com and has link [onme.link/1234](http://onme.link/1234). Now suppose OnMe user @jmatheson opens this link. Current implementation will reject @jmatheson from claiming the drink since @jmatheson has email enduro8@gmail.com which does not match drink's associated email. Same applies to twitter name or Phone Number.

Having all these I'd say it would take 30-40 hours for ios to
- 1. set up custom OnMe schema to communicate to custom deeplink similar to:(schema://onme.deeplink/someDrinkHash)
- 2. collect and query for device information to deeplink upon fresh AppStore launch.
- 3. Migrate API from Hoko to custom provider

And around 50-70 hours for backend to
- 1. Custom short url routs for deeplink.
- 2. Associating and storing device info with unclaimed drinks.
- 3. Generation and routing upon deeplink click. Communication with AppStore, OnMe app.
- 4. WebView for routing similar to 
![img_0292](https://cloud.githubusercontent.com/assets/3834896/25436324/a0ed7d22-2a9b-11e7-9b26-e07ba7241495.PNG)

The hardest part would be to correctly store User Device info through both Web and Native Apps to match drink's associated data.

**Comment by jmatheson** [comment]
@volkzayaz regarding 2, take a peek at the old code so you can see how it was implemented at a high level before. Then let's decide on our call tomorrow with @jidulberger

**Comment by jmatheson** [comment]
I am also wondering if there is a lower cost solution. That is a lot of hours.

**Comment by volkzayaz** [comment]
It's true that using another third party solution would be much cheaper. 
It's just the choice between 
a) cheap dependency that might be closed one day like Parse or Hoko.
b) more expensive own solution that will be stable.

Both options are fine, you just need to decide which one is more suitable.

**Comment by jmatheson** [comment]
Vlad to look at https://branch.io and report back

**Comment by volkzayaz** [comment]
Upon quick glance provides same features as Hoko. I'd say we can work with it.

**Comment by volkzayaz** [comment]
@jidulberger, It worked because you have both email and phone number on your account. 
The edge cases are taken care of. You will only be able to claim the drink if associated data matches the data on your account. For example, you bought a drink to +1-617-111-2222. 
Than if I open this drink using my own account App will refuse to claim it, because my number is not +1-617-111-2222. It's +380675777859.
Only user who has +1-617-111-2222 as his account will be able to claim it.
Same rules for sending drink using email, twitter. Receiver must have corresponding data in his account.

**Comment by jidulberger** [comment]
Great, thanks for clarifying that.
